### ISSUE TITLE
problem with 'koa-logger'

### ISSUE THREAD

**Issue by taha7ussein007** [joshuaslate/mkrn-starter#2]
i got this 
node_modules/koa-logger/index.js:36
  return async function logger (ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (home/mkrn-starter-master/api/index.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by Nassim33** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/12541080/34377912-a6793fb0-eaf3-11e7-991d-ac42b99e46a8.png)

**Comment by joshuaslate** [comment]
Hi,

Which version of Node are you two running? Also, which version of koa-logger?

Thanks,

Josh

**Comment by Nassim33** [comment]
Hi,

I have updated my Node version and now it's working.

Thanks

2017-12-27 11:18 GMT+01:00 Joshua Anderson Slate <notifications@github.com>:
